Restructure library dirs, drop dynamic_* libraries (#54)
* Drop all 'dynamic_*' libraries

* Reorganize headers and subdirs, add namespaced CMake targets

Moved all headers under a single include/novatel_edie directory at the repo root.

Split decoders/common into common/ and decoders/common to avoid a circular dependency between stream_interface and decoders/common.

Renamed:
- hw_interface/stream_interface -> stream_interface
- decoders/novatel -> decoders/oem

Added an edie_ prefix to all output names of libraries to avoid potential conflicts with other projects.

* Copy dependency shared libs to ${OUTPUT_DIR} on all platforms

* common_test does not require TEST_DATABASE_PATH

* Fix a typo

* CI: inspect build/out/bin dir

* Set RPATH to $ORIGIN for the copied third-party libs

* set CMAKE_CXX_STANDARD

* Add an aggregate novatel_edie::novatel_edie target

* Add Conan packaging support, support system deps, refactor CMake

* Add SetDefaultProfile.cmake

* conan_provider.cmake: fix missing runtime type detection for ClangCL

* Fix stream_interface folder name

* novatel_test -> oem_test

* CI: Add include/ to clang-format and editorconfig steps

* Copy shared libs only when building executables

* Make asciiFieldMap and jsonFieldMap non-static

The BaseEncoder static fields are not visible to the Encoder class in another shared library. Only works when linking statically.

Has no measurable impact on performance based on the test suite.

* Require Conan v2.4.0 or newer for CONAN_RUNTIME_LIB_DIRS

https://github.com/conan-io/conan/commit/29315889b45f24f83c6530a8bdb18b4c547e1cba

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -64,6 +64,12 @@ jobs:
       - name: Build
         run: cmake --build out/build --parallel --config ${{ env.BUILD_TYPE }}
 
+      - name: Inspect build outputs
+        if: env.OPERATING_SYSTEM == 'linux'
+        run: |
+          ls -lh out/build/bin/*
+          (cd out/build/bin/* && for f in *; do echo $f; objdump -p $f | grep -P 'RUNPATH|RPATH' || true; done)
+
       - name: Unit Tests
         run: ctest --test-dir out/build --build-config ${{ env.BUILD_TYPE }} --output-on-failure
 
@@ -103,7 +109,7 @@ jobs:
         sudo apt-get install -y clang-format
 
     - name: Check code formatting
-      run: find src examples \( -name '*.cpp' -o -name '*.hpp' \) -exec clang-format -Werror --style=file -n {} + || (echo "Clang-format failed! See the README if you don't know how to fix this." && exit 1)
+      run: find include src examples \( -name '*.cpp' -o -name '*.hpp' \) -exec clang-format -Werror --style=file -n {} + || (echo "Clang-format failed! See the README if you don't know how to fix this." && exit 1)
 
   # =========================================================
   # Editor Config Job
@@ -122,7 +128,7 @@ jobs:
       run: find . \( -name 'CMakeLists.txt' \) -exec editorconfig-checker {} \+ || { echo "EditorConfig check failed! See the README if you don't know how to fix this."; exit 1; }
 
     - name: Check C++ formatting
-      run: find src examples \( -name '*.cpp' -o -name '*.hpp' \) -exec editorconfig-checker {} \+ || { echo "EditorConfig check failed! See the README if you don't know how to fix this."; exit 1; }
+      run: find include src examples \( -name '*.cpp' -o -name '*.hpp' \) -exec editorconfig-checker {} \+ || { echo "EditorConfig check failed! See the README if you don't know how to fix this."; exit 1; }
 
   # =========================================================
   # Clang Tidy Job
@@ -185,10 +191,10 @@ jobs:
     - name: Generate HTML code coverage reports
       run: | 
         mkdir out/build/code-coverage
-        gcovr -r ./src/ ./out/build/ --exclude='.*/test/.*' --exclude='.*/dynamic_library/.*' --exclude='.*/version.h' --html --html-details -o ./out/build/code-coverage/index.html
+        gcovr -r ./src/ ./out/build/ --exclude='.*/test/.*' --exclude='.*/version.h' --html --html-details -o ./out/build/code-coverage/index.html
     
     - name: Coverage visualization in pipeline summary
-      run: gcovr -r ./src/ ./out/build/ --exclude='.*/test/.*' --exclude='.*/dynamic_library/.*' --exclude='.*/version.h' --exclude-unreachable-branches --print-summary -o ./out/build/coverage.xml
+      run: gcovr -r ./src/ ./out/build/ --exclude='.*/test/.*' --exclude='.*/version.h' --exclude-unreachable-branches --print-summary -o ./out/build/coverage.xml
 
     - name: Upload Artifacts
       uses: actions/upload-artifact@v4.3.0
