Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -119,8 +119,7 @@ jobs:
         sudo apt-get install -y clang-format
 
     - name: Check code formatting
-      run: |
-        find src examples \( -name '*.cpp' -o -name '*.hpp' \) -exec clang-format -Werror --style=file -n {} + || (echo "Clang-format failed! See the README if you don't know how to fix this." && exit 1)
+      run: find src examples \( -name '*.cpp' -o -name '*.hpp' \) -exec clang-format -Werror --style=file -n {} + || (echo "Clang-format failed! See the README if you don't know how to fix this." && exit 1)
 
   # =========================================================
   # Editor Config Job
@@ -136,7 +135,7 @@ jobs:
       uses: editorconfig-checker/action-editorconfig-checker@main
 
     - name: Check CMakeLists.txt formatting
-      run: editorconfig-checker --version
+      run: find . \( -name 'CMakeLists.txt' \) -exec editorconfig-checker {} \; || (echo "EditorConfig check failed for CMakeLists.txt files! See the README if you don't know how to fix this." && exit 1)
 
   # =========================================================
   # Clang Tidy Job
