Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -135,8 +135,11 @@ jobs:
       uses: editorconfig-checker/action-editorconfig-checker@main
 
     - name: Check CMakeLists.txt formatting
-      run: find . \( -name 'CMakeLists.txt' \) -exec editorconfig-checker {} \; || (echo "EditorConfig check failed for CMakeLists.txt files! See the README if you don't know how to fix this." && exit 1)
-
+      #run: find . \( -name 'CMakeLists.txt' \) -exec editorconfig-checker {} \; || (echo "EditorConfig check failed for CMakeLists.txt files! See the README if you don't know how to fix this." && exit 1)
+      run: |
+        set -e
+        find . \( -name 'CMakeLists.txt' \) -exec editorconfig-checker {} \;
+        echo "EditorConfig check passed for CMakeLists.txt files."
   # =========================================================
   # Clang Tidy Job
   # =========================================================
